version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - mongo
    environment:
      - MONGO_CONN_STR=mongodb://mongo:27017
      - API_PORT=8001
      - API_HOST=0.0.0.0
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
